# Generated by Django 2.2.27 on 2022-04-04 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220301_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Produtos'},
        ),
    ]
